openapi: 3.1.0
info:
  title: Web service for Gift Certificates system
  version: 1.0.0
tags:
  - name: tags
    description: CRD operations for tags
  - name: gift-certificates
    description: CRUD operations for gift certificates
paths:
  /tags:
    post:
      tags:
        - tags
      summary: Add a new tag
      description: Add a new tag
      operationId: addTag
      requestBody:
        description: Add a new tag
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TagRequestDto'
        required: false
      responses:
        '201':
          description: Successful operation
          content:
            text/plain:
              schema:
                type: integer
                description: ID of a created tag
        '400':
          description: Invalid input
          content:
            text/plain:
              schema:
                type: string
                description: Explanation which input is invalid
        default:
          description: Other error
          content:
            text/plain:
              schema:
                type: string
                description: Explanation which error occurred
    get:
      tags:
        - tags
      summary: Find all tags
      description: find all tags
      operationId: getAllTags
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TagResponseDto'
        default:
          description: Other errors
          content:
            text/plain:
              schema:
                type: string
                description: Explanation which error occurred
  /tags/{tagId}:
    get:
      tags:
        - tags
      summary: Find a tag by ID
      description: Find a tag by ID
      operationId: getTagById
      parameters:
        - name: tagId
          in: path
          description: ID of tag to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagResponseDto'
        '400':
          description: Invalid ID supplied
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: Tag not found
          content:
            text/plain:
              schema:
                type: string
        default:
          description: Other errors
          content:
            text/plain:
              schema:
                type: string
                description: Explanation which error occurred
    delete:
      tags:
        - tags
      summary: Delete a tag by ID
      description: Delete a tag by ID
      operationId: deleteTag
      parameters:
        - name: tagId
          in: path
          description: Tag ID to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Successful operation
        '400':
          description: Invalid ID supplied
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: Tag not found
          content:
            text/plain:
              schema:
                type: string
        default:
          description: Other errors
          content:
            text/plain:
              schema:
                type: string
  /gift-certificates:
    post:
      tags:
        - gift-certificates
      summary: Add a new gift certificate
      description: Add a new gift certificate
      operationId: addGiftCertificate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GiftCertificateRequestDto'
        required: false
      responses:
        '201':
          description: Successful operation
        '400':
          description: Invalid input
          content:
            text/plain:
              schema:
                type: string
        default:
          description: Other error
          content:
            text/plain:
              schema:
                type: string
    get:
      tags:
        - gift-certificates
      summary: Find all gift certificates with specified parameters
      description:  Find all gift certificates with specified parameters
      operationId: getAllGiftCertificates
      parameters:
        - name: sort
          in: query
          description: Gift certificates sort parameters
          required: false
          schema:
            type: array
            items:
              type: string
              pattern: "^(create_date|name),(asc|desc)$"
            maxItems: 2
        - name: search
          in: query
          description: Gift certificates search fields
          required: false
          schema:
            type: array
            items:
              type: string
              pattern: "^(name|description),"
            maxItems: 2
        - name: tagName
          in: query
          description: Tag name to search
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: Pagination limit value
          required: false
          schema:
            type: integer
            format: int64
        - name: page
          in: query
          description: Pagination page value
          required: false
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GiftCertificateResponseDto'
        '400':
          description: Invalid parameters supplied
          content:
            text/plain:
              schema:
                type: string
        default:
          description: Other error
          content:
            text/plain:
              schema:
                type: string
  /gift-certificates/{giftCertificateId}:
    get:
      tags:
        - gift-certificates
      summary: Find gift certificate by ID
      description: Find gift certificate by ID
      operationId: getGiftCertificateById
      parameters:
        - name: giftCertificateId
          in: path
          description: ID of gift certificate that needs to be found
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GiftCertificateResponseDto'
        '400':
          description: Invalid ID supplied
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: Gift certificate not found
          content:
            text/plain:
              schema:
                type: string
        default:
          description: Other error
          content:
            text/plain:
              schema:
                type: string
    put:
      tags:
        - gift-certificates
      summary: Update existing gift certificate
      description: Update existing gift certificate
      operationId: updateGiftCertificate
      parameters:
        - name: giftCertificateId
          in: path
          description: ID of gift certificate that needs to be updated
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GiftCertificateRequestDto'
        required: false
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: Gift certificate not found
          content:
            text/plain:
              schema:
                type: string
        default:
          description: Other error
          content:
            text/plain:
              schema:
                type: string
    delete:
      tags:
        - gift-certificates
      summary: Delete gift certificate by ID
      description: Delete gift certificate by ID
      operationId: deleteGiftCertificate
      parameters:
        - name: giftCertificateId
          in: path
          description: ID of the gift certificate that needs to be deleted
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Gift certificate not found
        default:
          description: Other error
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    TagRequestDto:
      type: object
      properties:
        name:
          type: string
          example: 'Birthday'
    TagResponseDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1235
        name:
          type: string
          example: 'Birthday'
    GiftCertificateRequestDto:
      type: object
      properties:
        name:
          type: string
          example: 'Birthday certificate'
        description:
          type: string
          example: 'Some description'
        price:
          type: number
          format: double
          example: 1500.00
        duration:
          type: integer
          format: int64
          example: 94301
        tags:
          type: array
          items:
            type: string
    GiftCertificateResponseDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 684354
        name:
          type: string
          example: 'Birthday certificate'
        description:
          type: string
          example: 'Some description'
        price:
          type: number
          format: double
          example: 1500.00
        duration:
          type: integer
          format: int64
          example: 94301
        createDate:
          type: string
          example: "2023-04-29T10:16Z"
        lastUpdateDate:
          type: string
          example: "2023-04-29T10:16Z"
        tags:
          type: array
          items:
            $ref: '#/components/schemas/TagResponseDto'