spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/gc
    username: root
    password: x2Aht9LND6g3
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/baeldung
          jwk-set-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs
      client:
        registration:
          google:
            client-id: google-id
            client-secret: google-secret
          facebook:
            client-id: facebook-id
            client-secret: facebook-secret
