spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/gc
    #url: jdbc:mysql://awseb-e-b9ihrmbsug-stack-awsebrdsdatabase-4mlr4hgnyqri.ch1kpk7wfhb0.eu-central-1.rds.amazonaws.com:3306/ebdb
    username: root
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/baeldung
          jwk-set-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs
      client:
        registration:
          google:
            client-id: google-id
            client-secret: google-secret
          facebook:
            client-id: facebook-id
            client-secret: facebook-secret
security:
  jwt:
    token:
      secret-key: ${JWT_SECRET}
sonar:
  login: admin
  password: admin
server:
  servlet:
    context-path: /gc-app